version: "3"
services:
  web:      
    image: mkt
    restart: always
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"